; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32@^6.9.0
board = freenove_esp32_s3_wroom
framework = arduino
monitor_speed = 115200
upload_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D CORE_DEBUG_LEVEL=0
	-D EI_PORTING_ARDUINO=0
	-D EI_CLASSIFIER_ALLOCATION_HEAP=1
	-D CONFIG_ESP_BROWNOUT_DET=0
	-I lib/milk_inferencing/src
	-I src/peripherals
	-I src/peripherals/sensors
	-I src/peripherals/camera
	-I src/peripherals/screen
	-DESP32QSPI_FREQUENCY=80000000
lib_deps = 
	knolleary/PubSubClient
	bblanchon/ArduinoJson
	0015/Library for OV5640 Auto Focus on ESP32 Camera@^0.1.1
	Adafruit_VL53L0X @ ^1.2.4
	adafruit/Adafruit NeoPixel@^1.15.2
	claws/BH1750@^1.3.0
	moononournation/GFX Library for Arduino@1.5.6
monitor_filters = esp32_exception_decoder, time
