#pragma once

// Board identifiers used to select the correct pinout header.
#define COFFEE_CAM_BOARD_WROVER_KIT 1
#define COFFEE_CAM_BOARD_ESP_EYE 2
#define COFFEE_CAM_BOARD_ESP32S3_EYE 3
#define COFFEE_CAM_BOARD_M5STACK_PSRAM 4
#define COFFEE_CAM_BOARD_M5STACK_V2_PSRAM 5
#define COFFEE_CAM_BOARD_M5STACK_WIDE 6
#define COFFEE_CAM_BOARD_M5STACK_ESP32CAM 7
#define COFFEE_CAM_BOARD_M5STACK_UNITCAM 8
#define COFFEE_CAM_BOARD_M5STACK_CAMS3_UNIT 9
#define COFFEE_CAM_BOARD_AI_THINKER 10
#define COFFEE_CAM_BOARD_TTGO_T_JOURNAL 11
#define COFFEE_CAM_BOARD_XIAO_ESP32S3 12
#define COFFEE_CAM_BOARD_ESP32_CAM_BOARD 13
#define COFFEE_CAM_BOARD_ESP32S3_CAM_LCD 14
#define COFFEE_CAM_BOARD_ESP32S2_CAM_BOARD 15
#define COFFEE_CAM_BOARD_DFROBOT_FIREBEETLE2_ESP32S3 16
#define COFFEE_CAM_BOARD_DFROBOT_ROMEO_ESP32S3 17

#ifndef COFFEE_CAM_BOARD
#define COFFEE_CAM_BOARD COFFEE_CAM_BOARD_ESP32S3_EYE
#endif

#if COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_WROVER_KIT
#define CAMERA_MODEL_WROVER_KIT
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_ESP_EYE
#define CAMERA_MODEL_ESP_EYE
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_ESP32S3_EYE
#define CAMERA_MODEL_ESP32S3_EYE
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_PSRAM
#define CAMERA_MODEL_M5STACK_PSRAM
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_V2_PSRAM
#define CAMERA_MODEL_M5STACK_V2_PSRAM
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_WIDE
#define CAMERA_MODEL_M5STACK_WIDE
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_ESP32CAM
#define CAMERA_MODEL_M5STACK_ESP32CAM
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_UNITCAM
#define CAMERA_MODEL_M5STACK_UNITCAM
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_M5STACK_CAMS3_UNIT
#define CAMERA_MODEL_M5STACK_CAMS3_UNIT
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_AI_THINKER
#define CAMERA_MODEL_AI_THINKER
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_TTGO_T_JOURNAL
#define CAMERA_MODEL_TTGO_T_JOURNAL
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_XIAO_ESP32S3
#define CAMERA_MODEL_XIAO_ESP32S3
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_ESP32_CAM_BOARD
#define CAMERA_MODEL_ESP32_CAM_BOARD
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_ESP32S3_CAM_LCD
#define CAMERA_MODEL_ESP32S3_CAM_LCD
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_ESP32S2_CAM_BOARD
#define CAMERA_MODEL_ESP32S2_CAM_BOARD
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_DFROBOT_FIREBEETLE2_ESP32S3
#define CAMERA_MODEL_DFRobot_FireBeetle2_ESP32S3
#elif COFFEE_CAM_BOARD == COFFEE_CAM_BOARD_DFROBOT_ROMEO_ESP32S3
#define CAMERA_MODEL_DFRobot_Romeo_ESP32S3
#else
#error "Unsupported COFFEE_CAM_BOARD selection"
#endif

#include "config/boards/camera_pins.h"
